route:
    receiver: 'telegram-receiver'
    repeat_interval: 24h
    group_by : [ alertname ]

receivers:
  - name: 'telegram-receiver'
    telegram_configs:
    - bot_token_file: "/config/.alert-manager-telegram-bot-token-file"
      send_resolved: true
      api_url: https://api.telegram.org
      chat_id: 377375680
      parse_mode: ''